#!/bin/bash

# Set path etc.
source ~/.zshenv

# xset for bitmap font
xset +fp ~/.fonts
xset fp rehash

# Configure X environment
compton --dbus &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
xset +fp /usr/share/fonts/local/ &
wp &
panel &
kb &
dunst &
vpsnotifyc &
urxvtd -f -o &

# Run local .xenv
source ~/.xenv

sxhkd -f 60 &

bspc config border_width        3
bspc config window_gap         25
bspc config bottom_padding     25

bspc config focused_border_color '#2f3133'
bspc config active_border_color  '#242628'
bspc config normal_border_color  '#242628'
bspc config urgent_border_color  '#ffaf00'
bspc config presel_border_color  '#5a5c5e'

bspc config split_ratio               0.50
bspc config auto_cancel               true
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config focus_follows_pointer     false
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

monitors=( 'VGA1' 'HDMI1' 'LVDS1'  'HDMI-0' 'DVI-D-0' 'DVI-I-1' ) # order is important
i=1
for m in "${monitors[@]}"; do
    if bspc query -M | grep "$m"; then
        bspc monitor "$m" -d $i-{1..6}
        let i++
    fi
done

bspc rule -a chromium desktop=1-2 border=off
bspc config -d 1-2 window_gap 0

bspc rule -a mplayer floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a feh floating=on
