#! /bin/sh

bspc config border_width        2
bspc config window_gap         10

bspc config focused_border_color '#505860'
bspc config active_border_color  '#102030'
bspc config normal_border_color  '#1d1f21'
bspc config urgent_border_color  '#ffaf00'
bspc config presel_border_color  '#4e9fb1'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_cursor true

bspc monitor VGA1 -d 1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9 1-0
bspc monitor LVDS1 -d 2-1 2-2 2-3 2-4 2-5 2-6 2-7 2-8 2-9 2-0

bspc monitor HDMI1 -d 1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9 1-0
bspc monitor DVI1 -d 2-1 2-2 2-3 2-4 2-5 2-6 2-7 2-8 2-9 2-0

bspc config -d 1-2 window_gap 0
bspc config -d 1-2 bottom_padding 2

bspc rule -a Gimp desktop=1-8 follow=on floating=on
bspc rule -a Chromium desktop=1-2 border=off
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh floating=on
