#! /bin/sh

# Set path etc.
source ~/.zshenv


# Configure monitors
if xrandr -q | grep 'HDMI-0 connected'; then
    xrandr --output HDMI-0 --primary
fi


# Configure X environment
feh --bg-scale ~/images/wallpapers/background1.png &
compton &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
xmodmap ~/.xmodmap &
panel &
xset r rate 250 25 &
for n in {8..12}; do xinput set-prop $n "Device Accel Constant Deceleration" 2.2; done & # I don't even care
vpsnotifyc &

sxhkd -f 60 &

bspc config border_width        2
bspc config window_gap         10

bspc config focused_border_color '#505860'
bspc config active_border_color  '#102030'
bspc config normal_border_color  '#1d1f21'
bspc config urgent_border_color  '#ffaf00'
bspc config presel_border_color  '#4e9fb1'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_cursor true

monitors=( 'VGA1' 'LVDS1'  'HDMI-0' 'DVI-I-1' ) # order is important
i=1
for m in ${monitors[@]}; do
    if bspc query -M | grep "$m"; then
        bspc monitor $m -d $i-{{1..9},0}
        let i++
    fi
done

bspc rule -a Chromium desktop=1-2 border=off
bspc config -d 1-2 window_gap 0
bspc config -d 1-2 bottom_padding 2

bspc rule -a mplayer floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a feh floating=on
